git pull -s subtree drupal 7.x
git pull -s subtree drush 7.x-4.x
git pull -s subtree i18n 7.x-1.x
git pull -s subtree variable 7.x-1.x
git pull -s subtree ctools 7.x-1.x
git pull -s subtree views 7.x-3.x
git pull -s subtree ckeditor 7.x-1.x
git pull -s subtree privatemsg 7.x-2.x
git pull -s subtree menu_block 7.x-2.x
